# Generated by Django 5.0.1 on 2024-06-10 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='date',
        ),
        migrations.AddField(
            model_name='articles',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Creation date'),
        ),
    ]
